name:                raytracer
version:             0.1.0.0
github:              "hgiddens/raytracer"
license:             BSD3
author:              "Hugh Giddens"
maintainer:          "hgiddens@gmail.com"
copyright:           "Hugh Giddens"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Ray Tracing in One Weekend

default-extensions:
- DeriveFoldable
- DeriveFunctor
- GeneralizedNewtypeDeriving
- NamedFieldPuns  
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- mono-traversable
- mtl
- random
- transformers

library:
  ghc-options:
    - -Wall
    - -O
  source-dirs: src

executables:
  raytracer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O
    dependencies:
    - raytracer

tests:
  raytracer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raytracer
